dev:
	@npm run dev

start:
	@npm run start

install:
	@npm install

clean:
	@rm -rf node_modules package-lock.json
	@echo " [*] cleaned backend"

build:
	@echo " [*] Building frontend..."
	@cd ../frontend && npm install && npm run build
	@echo " [*] Frontend build complete!"
